project:
  type: website
  output-dir: docs

website:
  title: "Pukar Bhandari"
  navbar:
    left:
      - href: about.qmd
        icon: person-circle
        text: About
      - href: projects.qmd
        icon: link-45deg
        text: Projects
      - href: resume.qmd
        icon: file-earmark-text-fill
        text: Resume

    right:
      - icon: mastodon
        href: https://urbanists.social/@arpuuk
      - icon: globe2
        href: https://bhandaripukar.com.np/
      - icon: linkedin
        href: https://www.linkedin.com/in/arpuuk
      - icon: github
        href: https://github.com/ar-puuk/
format:
  html:
    respect-user-color-scheme: true
    theme:
      light: "flatly"
      dark: "darkly"
    css: styles.css




