project:
  type: website
  output-dir: docs

website:
  title: "Pukar Bhandari"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume

    right:
      - icon: mastodon
        href: https://urbanists.social/@arpuuk
      - icon: bluesky
        href: https://bsky.app/profile/arpuuk.bsky.social
      - icon: linkedin
        href: www.linkedin.com/in/arpuuk
      - icon: github
        href: https://github.com/ar-puuk/

format:
  html:
    toc: true
    number-sections: true
    number-depth: 2
    html-math-method: katex
    respect-user-color-scheme: true
    theme:
      light: "flatly"
      dark: "darkly"
    css: styles.css
  typst:
    toc: true
    number-sections: true
    number-depth: 2
  docx:
    toc: true
    number-sections: true
    number-depth: 2
execute:
  eval: true
format-links:
  # - html
  - format: typst
    text: PDF
    icon: file-pdf
  - docx
prefer-html: true




