project:
  type: website
  output-dir: docs

website:
  title: "Pukar Bhandari"
  favicon: "assets/images/Headshot_PukarBhandari_July2025.png"
  navbar:
    left:
      - href: index.qmd
        icon: person-circle
        text: About
      - href: projects.qmd
        icon: link-45deg
        text: Projects
      - href: resume.qmd
        icon: file-earmark-text-fill
        text: Resume

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/arpuuk
      - icon: github
        href: https://github.com/ar-puuk/
  page-footer:
    left: 2025 Pukar Bhandari &#8729; Made with [Quarto](https://quarto.org)
    right:
      - text: Contact
        aria-label: Contact Form
        href: contact.qmd
      - text: License
        aria-label: License Details
        href: license.qmd
format:
  html:
    respect-user-color-scheme: true
    theme:
      light:
        - "flatly"
        - theme.scss
      dark:
        - "darkly"
        - theme.scss
    mainfont: "Poppins"
    monofont: "Fira Code"
    css: assets/css/index.css
# include-in-header:
#   - _includes/preload-fonts.html
