name: website
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12 # Pin specific python version
  - pandas
  - geopandas
  - pyproj>=3.6
  - proj>=9.3
  - shapely
  - folium
  - requests
  - numpy
  - pygris
  - polars
  - duckdb
  - pip
