name: website
# Run this to create: conda env create --prefix ./env --file environment.yml
# Run this to update: conda env update --prefix ./env --file environment.yml --prune
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12 # Pin specific python version
  - pandas
  - geopandas
  - pyproj>=3.6
  - proj>=9.3
  - shapely
  - folium
  - requests
  - numpy
  - pygris
  - polars
  - duckdb
  # Core dependencies for Quarto execution
  - ipykernel
  - pyyaml
  - nbformat
  - nbclient
  - pip
